// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Date: typeof import('./src/components/calendar/date.vue')['default']
    Form: typeof import('./src/components/form/index.vue')['default']
    List: typeof import('./src/components/list/index.vue')['default']
    Month: typeof import('./src/components/calendar/month.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/form/select/index.vue')['default']
    Uploader: typeof import('./src/components/form/uploader/index.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCascader: typeof import('vant/es')['Cascader']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
